name: nutricare_mvp
description: MVP for NutriCare - Offline-first nutrition companion
version: 1.0.0
environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    sqflite: ^2.3.0
    path_provider: ^2.0.15
    encrypt: ^5.0.1
    firebase_core: ^4.1.1
    cloud_firestore: ^6.0.2
    firebase_auth: ^6.1.0
    qr_flutter: ^4.1.0
    tflite_flutter: ^0.11.0
    speech_to_text: ^7.3.0
    flutter_tts: ^4.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
